<?php
    class Laser{
        public function caracteristiques(){
            echo "Disque laser<br>";
        }
    }

    class CD extends Laser{
        public function caracteristiques()
        {
            parent::caracteristiques(); // TODO: Change the autogenerated stub
            echo "Capacité : 700 Mo<br>";
        }
    }

    class DVD extends Laser{
        public function caracteristiques()
        {
            parent::caracteristiques(); // TODO: Change the autogenerated stub
            echo "Capacité : 4,7 Go<br>";
        }
    }

    class Blue extends Laser{
        public function caracteristiques()
        {
            parent::caracteristiques(); // TODO: Change the autogenerated stub
            echo "Capacité : 25 Go<br>";
        }
    }
?>